In [1]:
import numpy as np
import h5py


In [2]:
filename = "/mnt/raid1/maria/GOLD_XYZ_OSC.0001_1024.hdf5"
f = h5py.File(filename, 'r')
Y = f['Y']

In [3]:
new_classes = ['OOK', '4ASK', '8ASK','BPSK', 'QPSK', '8PSK', 'M-PSK', 'M-APSK','16QAM', '32QAM', 'M-QAM', 'AM-SSB', 'AM-DSB', 'FM', 'GMSK', 'OQPSK']
print(len(new_classes))

16


In [4]:
print(Y[745471][6].dtype)

int64


In [5]:
index = 0
size = 4096*26*6


In [6]:
Y_grouped = np.zeros((4096*26*24, 16), dtype='int')
Y_grouped[index:index+size,] = np.copy(Y[index:index+size, :16])
print(Y[0, :7], Y_grouped[0, :7])
print(Y[450450, :7] , Y_grouped[450450, :7])
print(Y[745471, :7] , Y_grouped[745471, :7])

[1 0 0 0 0 0 0] [1 0 0 0 0 0 0]
[0 0 0 0 1 0 0] [0 0 0 0 1 0 0]
[0 0 0 0 0 0 1] [0 0 0 0 0 0 0]


In [7]:
index += size
size = 4096*26*2

In [9]:
min = 4096*26

In [10]:
Y_grouped[index:index+size] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0],]*size)
print(Y[index][:15], Y_grouped[index])
print(Y[index+min][:15],Y_grouped[index+min] )
print(Y[index+min+1][:15],Y_grouped[index+min + 1] )
print(Y[index+size-1][:15],Y_grouped[index+size-1])
print(Y[index+size][:15],Y_grouped[index+size])

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0] [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0] [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0] [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [11]:
index += size

In [12]:
size = 4096*4*26
min = 4096*26

In [13]:
Y_grouped[index:index+size] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0],]*size)
print(Y[index], Y_grouped[index])
print(Y[index + min],Y_grouped[index+min] )
print(Y[index + 2*min],Y_grouped[index + 2*min] )
print(Y[index+size-1],Y_grouped[index+size-1])
print(Y[index+size], Y_grouped[index+size])

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
index += size
size = 4096*2*26

In [15]:
Y_grouped[index:index+min] =np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0 ,0 ,0 ,0 ,0],]*min)
Y_grouped[index+min:index+size] =np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0 ,0 ,0 ,0],]*min)
print(Y[index], Y_grouped[index])
print(Y[index + min-1],Y_grouped[index+min-1] )
print(Y[index+size-1],Y_grouped[index+size-1])


[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


In [16]:
index = index+size
size = 4096*3*26

In [17]:
index

1490944

In [18]:
Y_grouped[index:index+size] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0 ,0 ,0],]*size)
print(Y[index], Y_grouped[index])
print(Y[index + min],Y_grouped[index+min] )
print(Y[index+size-1],Y_grouped[index+size-1])


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


In [19]:
index = index+size
size = 4096*2*26
index

1810432

In [20]:
Y_grouped[index:index+size] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0 ,0],]*size)
print(Y[index], Y_grouped[index])
print(Y[index+ min - 1], Y_grouped[index + min - 1])
print(Y[index+size-1],Y_grouped[index+size-1])


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]


In [21]:
index = index+size
size = 4096*2*26
index

2023424

In [22]:
Y_grouped[index:index+size] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0 ,0],]*size)
print(Y[index], Y_grouped[index])
print(Y[index+ min - 1], Y_grouped[index + min - 1])
print(Y[index+ min], Y_grouped[index + min])
print(Y[index+size-1],Y_grouped[index+size-1])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]


In [23]:
index += size
size = 4096*3*26
print(index)

2236416


In [24]:
Y_grouped[index:index+min] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0 ,0],]*min)
Y_grouped[index+min:index+2*min] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1 ,0],]*min)
Y_grouped[index+2*min:index+size] = np.array([[0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,1],]*min)
print(Y[index], Y_grouped[index])
print(Y[index+ min - 1], Y_grouped[index + min - 1])
print(Y[index+ min], Y_grouped[index + min])
print(Y[index+ 2*min - 1], Y_grouped[index + 2*min-1])
print(Y[index+ 2*min], Y_grouped[index + 2*min])
print(Y[index+size-1],Y_grouped[index+size-1])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [25]:
X = f['X']
SNR = f['Z']


In [26]:
np.random.seed(2018)
from sklearn.utils import shuffle
X_shuffled, Y_shuffled, lbl_shuffled = shuffle(X[:], Y_grouped[:], SNR[:], random_state = 2018)

In [27]:
print(X_shuffled.shape)
print(Y_shuffled.shape)
print(lbl_shuffled.shape)
print(X_shuffled.dtype)

(2555904, 1024, 2)
(2555904, 16)
(2555904, 1)
float32


In [ ]:
X_shuffled = X_shuffled.astype('float16')

In [29]:
print(X_shuffled.dtype)

float16


In [30]:
np.save("/mnt/raid1/maria/Xg_shuffled.npy" , X_shuffled)
np.save("/mnt/raid1/maria/Yg_shuffled.npy" , Y_shuffled)
np.save("/mnt/raid1/maria/SNRg_shuffled.npy" , lbl_shuffled)